### PR TITLE
Switch arm64 and ppc64 builds to use Azure

### PR DESCRIPTION
**Pull request by traversaro**
For some reason the arm64 and ppc64 build were not triggered after merging of https://github.com/conda-forge/diffutils-feedstock/pull/3 and https://github.com/conda-forge/diffutils-feedstock/pull/4, so I bumped the build number to make sure they are triggered.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Actually the problem is https://github.com/conda-forge/status/issues/122 .

**Comment by traversaro** [comment]
> 
> 
> Actually the problem is [conda-forge/status#122](https://github.com/conda-forge/status/issues/122) .

I guess we can simple switch to azure also for arm64 and ppc64 builds.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
You can also do cross compiling by using https://github.com/conda-forge/status/issues/122#issuecomment-959807945

**Comment by traversaro** [comment]
> 
> 
> You can also do cross compiling by using [conda-forge/status#122 (comment)](https://github.com/conda-forge/status/issues/122#issuecomment-959807945)

Cool, I was not aware of this. I will try this as in any case there are no tests in this package.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
And thanks for the fix @isuruf!

**Comment by traversaro** [comment]
Thanks to cross-compiling, the build time on arm64/ppc64 is reduced to ~5 minutes.

**Comment by traversaro** [comment]
> I will try this as in any case there are no tests in this package.

Actually it seems that simple tests are there: https://github.com/conda-forge/diffutils-feedstock/blob/2e14a7824e3b98964c2ecfbdd375a81071ccb0ed/recipe/meta.yaml#L24 . However, it seems that are executed anyhow, not sure how.

**Comment by isuruf** [comment]
> However, it seems that are executed anyhow, not sure how.

Using QEMU

**Comment by traversaro** [comment]
> 
> 
> > However, it seems that are executed anyhow, not sure how.
> 
> Using QEMU

Great, then as long as the build system supports it, using cross-compiling seems to be always a better idea w.r.t. to emulation, as you still run tests while running a faster compilation.

**Comment by traversaro** [comment]
> > > However, it seems that are executed anyhow, not sure how.
> > 
> > 
> > Using QEMU
> 
> Great, then as long as the build system supports it, using cross-compiling seems to be always a better idea w.r.t. to emulation, as you still run tests while running a faster compilation.

Actually this is not completly true, as for some build systems (for example in C++/CMake) the tests normally need to run as part of the build step, and so they can't run if you are cross-compiling.

**Pull request merged**
